/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FibonacciCalculator {
        "calculateFibonacci": (n?: number) => Promise<void>;
    }
}
declare global {
    interface HTMLFibonacciCalculatorElement extends Components.FibonacciCalculator, HTMLStencilElement {
    }
    var HTMLFibonacciCalculatorElement: {
        prototype: HTMLFibonacciCalculatorElement;
        new (): HTMLFibonacciCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "fibonacci-calculator": HTMLFibonacciCalculatorElement;
    }
}
declare namespace LocalJSX {
    interface FibonacciCalculator {
    }
    interface IntrinsicElements {
        "fibonacci-calculator": FibonacciCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fibonacci-calculator": LocalJSX.FibonacciCalculator & JSXBase.HTMLAttributes<HTMLFibonacciCalculatorElement>;
        }
    }
}
